### ISSUE TITLE
hone pod autoscaling rates

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk-autoscaler#1]
Pod autoscaling rates need to be set to rational defaults.

Also, it's a good idea to have different scale-up and scale-down rates. (Scale-down should probably be much slower.)

Also, the pre- and post-processing pods need to be added into the autoscaler script.

**Comment by willgraf** [comment]
This is no longer necessary, we are using the autoscaler to turn on/off the GPU and using k8s HPAs to scale pods from 1 to many.
