### ISSUE TITLE
loop sleep duration

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk-autoscaler#3]
At the end of the loop in `autoscale.sh`, the script waits for a variable amount of time. Apparently, giving the GPUs enough time to startup is a necessity, so it will wait for a long time when it expects a GPU to be starting up. We should move to a system where the script actually verifies how many GPUs are up and what their statuses are (and checks pods creation statuses, if necessary) in order to wait intelligently, rather than just guessing how long GPU startup might take.

**Comment by willgraf** [comment]
This is no longer relevant. I am closing this.
